TRUNCATE TABLE reading_list_entries CASCADE;
TRUNCATE TABLE reviews CASCADE;
TRUNCATE TABLE book_authors CASCADE;
TRUNCATE TABLE book_genres CASCADE;
TRUNCATE TABLE books CASCADE;
TRUNCATE TABLE authors CASCADE;
TRUNCATE TABLE genres CASCADE;